# Docker Compose for Department Reviews
# Easy one-command deployment for non-technical reviewers

version: '3.8'

services:
  # Frontend service for the main dapp interface
  frontend-review:
    build:
      context: ./the-project/packages/frontend
      dockerfile: Dockerfile.review
    ports:
      - '3000:3000'
    environment:
      - VITE_APP_MODE=demo
      - VITE_DEMO_MODE=true
      - VITE_APP_NAME=The Project - Cross-Chain DApp
      - VITE_APP_VERSION=1.5.0
      - VITE_DEMO_FEATURES_ENABLED=true
      - VITE_SHOW_TOOLTIPS=true
      - VITE_GUIDED_TOUR=true
    depends_on:
      - api-review
    networks:
      - review-network

  # API service with demo data
  api-review:
    build:
      context: ./packages/api
      dockerfile: Dockerfile.review
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=demo
      - DEMO_MODE=true
      - API_PORT=8080
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - review-network

  # Documentation service
  docs-review:
    image: nginx:alpine
    ports:
      - '8081:80'
    volumes:
      - ./review-docs:/usr/share/nginx/html:ro
      - ./nginx-review.conf:/etc/nginx/nginx.conf:ro
    networks:
      - review-network

networks:
  review-network:
    driver: bridge

volumes:
  review-data:
